t=['qq','aa','ss']
print('邀请'+t[0]+'参加')
print('邀请'+t[1]+'参加')
print('邀请'+t[2]+'参加')
print(t[2]+'无法参加')
t[2]='pp'
print('邀请'+t[0]+'参加')
print('邀请'+t[1]+'参加')
print('邀请'+t[2]+'参加')
print('找到更大地方再拉3个人')
t.insert(0,'ww')
t.insert(1,'ee')
t.append('rr')
print(t)
print('邀请'+t[0]+'参加')
print('邀请'+t[1]+'参加')
print('邀请'+t[2]+'参加')
print('邀请'+t[3]+'参加')
print('邀请'+t[4]+'参加')
print('邀请'+t[5]+'参加')
print('场地只能2人')
cc=t.pop()
print('不能邀请'+cc+'参加')
cc=t.pop()
print('不能邀请'+cc+'参加')
cc=t.pop()
print('不能邀请'+cc+'参加')
cc=t.pop()
print('不能邀请'+cc+'参加')
print('邀请'+t[0]+'参加')
print('邀请'+t[1]+'参加')
del t[0]
print(t)
del t[0]
print(t)

